export const METRICS = {
  tss: {
    title: "TSS",
    tag: "Training Stress Score",
    body: "Eén getal dat vat hoe zwaar een rit was: langer en harder betekent meer TSS. Een rustig duurritje van een uur zit rond de 50; een pittige intervaltraining tikt al snel richting 100. We gebruiken het om je belasting over de week in balans te houden.",
    color: "oklch(0.55 0.14 35)",
    tint: "oklch(0.93 0.05 40)",
  },
  ftp: {
    title: "FTP",
    tag: "Functional Threshold Power",
    body: "Het vermogen in watt dat je ongeveer een uur lang kunt volhouden — je belangrijkste maat voor fietsconditie. Bijna al je trainingszones worden hiervan afgeleid, dus als je FTP stijgt, schuift je hele plan mee omhoog.",
    color: "oklch(0.5 0.14 250)",
    tint: "oklch(0.92 0.045 250)",
  },
  if: {
    title: "Intensiteit",
    tag: "Intensity Factor",
    body: "Hoe zwaar een rit aanvoelde ten opzichte van jouw FTP. Rond de 0,75 is een comfortabele duurrit, boven de 0,90 wordt het echt stevig. Handig om in één oogopslag te zien of een dag licht of pittig was.",
    color: "oklch(0.5 0.14 162)",
    tint: "oklch(0.91 0.05 165)",
  },
  sweetspot: {
    title: "Sweetspot",
    tag: "Zone 3 · 88–94% FTP",
    body: "Het zoete punt net onder je drempel: zwaar genoeg om flink sterker te worden, licht genoeg om het lang vol te houden zonder dagenlang kapot te zijn. Daarom vormt het de ruggengraat van je opbouwfase.",
    color: "oklch(0.46 0.13 168)",
    tint: "oklch(0.91 0.05 168)",
  },
  rampe: {
    title: "Weekbelasting",
    tag: "Ramp rate",
    body: "Hoeveel je trainingsbelasting deze week oploopt ten opzichte van vorige week. We houden de stijging bewust geleidelijk — zo word je sterker zonder over de rand van overbelasting te gaan.",
    color: "oklch(0.5 0.14 70)",
    tint: "oklch(0.92 0.05 75)",
  },
  vorm: {
    title: "Vorm",
    tag: "Form / Freshness (TSB)",
    body: "De balans tussen je opgebouwde conditie en je vermoeidheid. Positief betekent fris en wedstrijdklaar, negatief betekent dat je middenin een zware blok zit. Vlak voor een doel sturen we deze waarde bewust de plus in.",
    color: "oklch(0.5 0.13 300)",
    tint: "oklch(0.92 0.045 300)",
  },
  ctl: {
    title: "Fitheid",
    tag: "Chronic Training Load (CTL)",
    body: "Je gemiddelde trainingsbelasting over de afgelopen 6 weken. Stijgt langzaam als je consistent traint, daalt als je stopt. Hoe hoger dit getal, hoe meer je lichaam gewend is aan inspanning — maar het zegt niets over hoe fris je bent.",
    color: "oklch(0.5 0.14 250)",
    tint: "oklch(0.92 0.045 250)",
  },
  atl: {
    title: "Vermoeidheid",
    tag: "Acute Training Load (ATL)",
    body: "Je gemiddelde belasting over de afgelopen 7 dagen. Reageert snel op zware trainingen en daalt snel bij rust. Wanneer dit getal je fitheid (CTL) overstijgt, bouw je vermoeidheid op — dat is normaal in een trainingsblok, maar moet niet te lang duren.",
    color: "oklch(0.55 0.12 35)",
    tint: "oklch(0.93 0.05 40)",
  },
  balansscore: {
    title: "Balansscore",
    tag: "Gewogen herstelindex",
    body: "Een samengestelde score (0–100) op basis van je trainingsbalans (TSB), hartslag­variabiliteit (HRV) en rusthartslag. Hoe hoger de score, hoe meer je lichaam klaar is voor inspanning. De weging: TSB 50%, HRV 35%, rusthartslag 15%.",
    color: "oklch(0.5 0.14 248)",
    tint: "oklch(0.92 0.045 248)",
  },
  vermogen: {
    title: "Gem. vermogen",
    tag: "Normalized Power (NP)",
    body: "Het gewogen gemiddelde vermogen van een rit, gecorrigeerd voor variatie. Een rit met veel pieken en dalen voelt zwaarder aan dan hetzelfde gemiddelde op een constant tempo — NP vangt dat verschil.",
    color: "oklch(0.5 0.14 70)",
    tint: "oklch(0.92 0.05 75)",
  },
};
